### PR TITLE
Add Each macro :tada:

### PR DESCRIPTION
**Pull request by yogeshjain999**
Screenshot 2021-08-30 at 9 24 26 AM

### CODE REVIEW

**Comment by seuros** [comment]
I think ForEach will be a better naming. Cc @apotonick

**Comment by emaglio** [comment]
this is great!!

**Comment by emaglio** [comment]
wondering if we could have something similar for activities?? or you must use Operations and build your own macro in activities..

**Comment by yogeshjain999** [comment]
@emaglio Good point!
I think we can do that when we remove `Operation` references from `Wrap`. There is already a TODO for this in `gemspec`.

**Comment by yogeshjain999** [comment]
> I think ForEach will be a better naming. Cc @apotonick

Seems good to me too!

**Comment by seuros** [comment]
@yogeshjain999 can you rebase/fix naming ?

**Comment by apotonick** [comment]
I can check it out in the coming weeks, I need it for Reform 3.

**Comment by yogeshjain999** [comment]
> @yogeshjain999 can you rebase/fix naming ?

Sure, will do.

**Comment by seuros** [comment]
Can we have this Macro rebased and merged ?

**Comment by yogeshjain999** [comment]
> Can we have this Macro rebased and merged ?

I'm actually waiting for @apotonick's input regarding the way `each` is used over here https://github.com/trailblazer/trailblazer-macro/pull/38/files#diff-053d99a4fce30bb3e7a1d3b814f3608611db2f5ef3841afa5059c42754af9110R21

**Pull request merged**
